(function(g){var u,t,z=function(i,q){var j=0;this.complete=function(){j+=1;j===q&&i()}};u=function(i){var q=this,j,r,e={namespace:"file_upload",uploadFormFilter:function(){return true},fileInputFilter:function(){return true},cssClass:"file_upload",dragDropSupport:true,dropZone:i,url:function(a){return a.attr("action")},method:function(a){return a.attr("method")},fieldName:function(a){return a.attr("name")},formData:function(a){return a.serializeArray()},multipart:true,multiFileRequest:false,withCredentials:false,
forceIframeUpload:false},k={},l={},o=/^http(s)?:\/\//,p,f=function(){return typeof XMLHttpRequest!=="undefined"&&typeof File!=="undefined"&&(!e.multipart||typeof FormData!=="undefined"||typeof FileReader!=="undefined")},s=function(){if(e.dragDropSupport){if(typeof e.onDocumentDragEnter==="function")k["dragenter."+e.namespace]=function(a){e.onDocumentDragEnter(a)};if(typeof e.onDocumentDragLeave==="function")k["dragleave."+e.namespace]=function(a){e.onDocumentDragLeave(a)};k["dragover."+e.namespace]=
q.onDocumentDragOver;k["drop."+e.namespace]=q.onDocumentDrop;g(document).bind(k);if(typeof e.onDragEnter==="function")l["dragenter."+e.namespace]=function(a){e.onDragEnter(a)};if(typeof e.onDragLeave==="function")l["dragleave."+e.namespace]=function(a){e.onDragLeave(a)};l["dragover."+e.namespace]=q.onDragOver;l["drop."+e.namespace]=q.onDrop;e.dropZone.bind(l)}r.bind("change."+e.namespace,q.onChange)},v=function(){g.each(k,function(a,b){g(document).unbind(a,b)});g.each(l,function(a,b){e.dropZone.unbind(a,
b)});r.unbind("change."+e.namespace)},y=function(a,b,c,d){if(typeof d.onProgress==="function")c.upload.onprogress=function(h){d.onProgress(h,a,b,c,d)};if(typeof d.onLoad==="function")c.onload=function(h){d.onLoad(h,a,b,c,d)};if(typeof d.onAbort==="function")c.onabort=function(h){d.onAbort(h,a,b,c,d)};if(typeof d.onError==="function")c.onerror=function(h){d.onError(h,a,b,c,d)}},x=function(a){if(typeof a.url==="function")return a.url(a.uploadForm||j);return a.url},D=function(a){if(typeof a.method===
"function")return a.method(a.uploadForm||j);return a.method},A=function(a){if(typeof a.fieldName==="function")return a.fieldName(a.fileInput||r);return a.fieldName},B=function(a){var b;if(typeof a.formData==="function")return a.formData(a.uploadForm||j);else if(g.isArray(a.formData))return a.formData;else if(a.formData){b=[];g.each(a.formData,function(c,d){b.push({name:c,value:d})});return b}return[]},J=function(a,b,c){if(c)a.setRequestHeader("X-Requested-With","XMLHttpRequest");else if(b.withCredentials)a.withCredentials=
true;if(g.isArray(b.requestHeaders))g.each(b.requestHeaders,function(d,h){a.setRequestHeader(h[0],h[1])});else b.requestHeaders&&g.each(b.requestHeaders,function(d,h){a.setRequestHeader(d,h)})},K=function(a,b,c){var d=new FormData,h;g.each(B(c),function(m,n){d.append(n.name,n.value)});for(h=0;h<a.length;h+=1)d.append(A(c),a[h]);b.send(d)},L=function(a,b){var c=new FileReader;c.onload=function(d){a.content=d.target.result;b()};c.readAsBinaryString(a)},M=function(a,b,c,d){var h="";g.each(d,function(m,
n){h+="--"+a+'\r\nContent-Disposition: form-data; name="'+unescape(encodeURIComponent(n.name))+'"\r\n\r\n'+unescape(encodeURIComponent(n.value))+"\r\n"});g.each(b,function(m,n){h+="--"+a+'\r\nContent-Disposition: form-data; name="'+unescape(encodeURIComponent(c))+'"; filename="'+unescape(encodeURIComponent(n.name))+'"\r\nContent-Type: '+n.type+"\r\n\r\n"+n.content+"\r\n"});h+="--"+a+"--\r\n";return h},N=function(a,b,c){var d="----MultiPartFormBoundary"+(new Date).getTime(),h,m;b.setRequestHeader("Content-Type",
"multipart/form-data; boundary="+d);h=new z(function(){b.sendAsBinary(M(d,a,A(c),B(c)))},a.length);for(m=0;m<a.length;m+=1)L(a[m],h.complete)},E=function(a,b,c,d){var h=x(d),m;if(o.test(h)){var n=location.host;m=location.protocol.length+2;var w=h.indexOf(n,m);n=w+n.length;m=(w===m||w===h.indexOf("@",m)+1)&&(h.length===n||g.inArray(h.charAt(n),["/","?","#"])!==-1)?true:false}else m=true;y(a,b,c,d);c.open(D(d),h,true);J(c,d,m);if(d.multipart){a=typeof b==="number"?[a[b]]:a;if(typeof FormData!=="undefined")K(a,
c,d);else typeof FileReader!=="undefined"?N(a,c,d):g.error("Browser does neither support FormData nor FileReader interface")}else{d=a[b];m&&c.setRequestHeader("X-File-Name",unescape(encodeURIComponent(d.name)));c.setRequestHeader("Content-Type",d.type);c.send(d)}},F=function(a,b,c,d,h){var m=new XMLHttpRequest,n=g.extend({},e);n.fileInput=c;n.uploadForm=d;typeof n.initUpload==="function"?n.initUpload(a,b,h,m,n,function(){E(b,h,m,n)}):E(b,h,m,n)},G=function(a,b,c,d){var h;if(e.multiFileRequest)F(a,
b,c,d);else for(h=0;h<b.length;h+=1)F(a,b,c,d,h)},O=function(a,b,c){var d=B(c);b.find(":input").not(":disabled").attr("disabled",true).addClass(c.namespace+"_disabled");g.each(d,function(h,m){g('<input type="hidden"/>').attr("name",m.name).val(m.value).addClass(c.namespace+"_form_data").appendTo(b)});a.attr("name",A(c)).appendTo(b)},P=function(a,b,c){a.detach();b.find("."+c.namespace+"_disabled").removeAttr("disabled").removeClass(c.namespace+"_disabled");b.find("."+c.namespace+"_form_data").remove()},
H=function(a,b,c,d){var h=b.attr("action"),m=b.attr("method"),n=b.attr("target");c.unbind("abort").bind("abort",function(w){c.readyState=0;c.unbind("load").attr("src","javascript".concat(":false;"));typeof d.onAbort==="function"&&d.onAbort(w,[{name:a.val(),type:null,size:null}],0,c,d)}).unbind("load").bind("load",function(w){c.readyState=4;typeof d.onLoad==="function"&&d.onLoad(w,[{name:a.val(),type:null,size:null}],0,c,d);g('<iframe src="javascript:false;" style="display:none"></iframe>').appendTo(b).remove()});
b.attr("action",x(d)).attr("method",D(d)).attr("target",c.attr("name"));O(a,b,d);c.readyState=2;b.get(0).submit();P(a,b,d);b.attr("action",h).attr("method",m).attr("target",n)},Q=function(a,b,c){var d=g('<iframe src="javascript:false;" style="display:none" name="iframe_'+e.namespace+"_"+(new Date).getTime()+'"></iframe>'),h=g.extend({},e);h.fileInput=b;h.uploadForm=c;d.readyState=0;d.abort=function(){d.trigger("abort")};d.bind("load",function(){d.unbind("load");typeof h.initUpload==="function"?h.initUpload(a,
[{name:b.val(),type:null,size:null}],0,d,h,function(){H(b,c,d,h)}):H(b,c,d,h)}).appendTo(c)},I=function(){j=(i.is("form")?i:i.find("form")).filter(e.uploadFormFilter)},C=function(){r=j.find("input:file").filter(e.fileInputFilter)};this.onDocumentDragOver=function(a){if(typeof e.onDocumentDragOver==="function"&&e.onDocumentDragOver(a)===false)return false;a.preventDefault()};this.onDocumentDrop=function(a){if(typeof e.onDocumentDrop==="function"&&e.onDocumentDrop(a)===false)return false;a.preventDefault()};
this.onDragOver=function(a){if(typeof e.onDragOver==="function"&&e.onDragOver(a)===false)return false;var b=a.originalEvent.dataTransfer;if(b&&b.files){b.dropEffect=b.effectAllowed="copy";a.preventDefault()}};this.onDrop=function(a){if(typeof e.onDrop==="function"&&e.onDrop(a)===false)return false;var b=a.originalEvent.dataTransfer;b&&b.files&&f()&&G(a,b.files);a.preventDefault()};this.onChange=function(a){if(typeof e.onChange==="function"&&e.onChange(a)===false)return false;var b=g(a.target),c=g(a.target.form);
if(c.length===1){b.data("file_upload_form",c);var d=b.clone(true);g("<form/>").append(d).get(0).reset();b.after(d).detach();C()}else c=b.data("file_upload_form");!e.forceIframeUpload&&a.target.files&&f()?G(a,a.target.files,b,c):Q(a,b,c)};this.init=function(a){if(a){g.extend(e,a);p=a}I();C();if(i.data(e.namespace))g.error('FileUpload with namespace "'+e.namespace+'" already assigned to this element');else{i.data(e.namespace,q).addClass(e.cssClass);e.dropZone.not(i).addClass(e.cssClass);s()}};this.options=
function(a){var b,c,d,h;if(typeof a==="undefined")return g.extend({},e);p&&g.extend(p,a);v();g.each(a,function(m,n){switch(m){case "namespace":g.error("The FileUpload namespace cannot be updated.");return;case "uploadFormFilter":h=d=true;break;case "fileInputFilter":h=true;break;case "cssClass":b=e.cssClass;break;case "dropZone":c=e.dropZone}e[m]=n});d&&I();h&&C();if(typeof b!=="undefined"){i.removeClass(b).addClass(e.cssClass);(c?c:e.dropZone).not(i).removeClass(b);e.dropZone.not(i).addClass(e.cssClass)}else if(c){c.not(i).removeClass(e.cssClass);
e.dropZone.not(i).addClass(e.cssClass)}s()};this.option=function(a,b){var c;if(typeof b==="undefined")return e[a];c={};c[a]=b;q.options(c)};this.destroy=function(){v();i.removeData(e.namespace).removeClass(e.cssClass);e.dropZone.not(i).removeClass(e.cssClass)}};t={init:function(i){return this.each(function(){(new u(g(this))).init(i)})},option:function(i,q,j){j=j?j:"file_upload";var r=g(this).data(j);if(r){if(typeof i==="string")return r.option(i,q);return r.options(i)}else g.error('No FileUpload with namespace "'+
j+'" assigned to this element')},destroy:function(i){i=i?i:"file_upload";return this.each(function(){var q=g(this).data(i);q?q.destroy():g.error('No FileUpload with namespace "'+i+'" assigned to this element')})}};g.fn.fileUpload=function(i){if(t[i])return t[i].apply(this,Array.prototype.slice.call(arguments,1));else if(typeof i==="object"||!i)return t.init.apply(this,arguments);else g.error("Method "+i+" does not exist on jQuery.fileUpload")}})(jQuery);
(function(g){var u,t,z=function(i,q){var j,r;if(!q.test(i.type))return null;j=document.createElement("img");if(typeof URL!=="undefined"&&typeof URL.createObjectURL==="function"){j.src=URL.createObjectURL(i);j.onload=function(){URL.revokeObjectURL(this.src)};return j}if(typeof FileReader!=="undefined"){r=new FileReader;if(typeof r.readAsDataURL==="function"){r.onload=function(e){j.src=e.target.result};r.readAsDataURL(i);return j}}return null};u=function(i,q){var j=this,r,e;this.requestHeaders={Accept:"application/json, text/javascript, */*; q=0.01"};
this.dropZone=i;this.imageTypes=/^image\/(gif|jpeg|png)$/;this.previewSelector=".file_upload_preview";this.progressSelector=".file_upload_progress div";this.cancelSelector=".file_upload_cancel button";this.cssClassSmall="file_upload_small";this.cssClassLarge="file_upload_large";this.cssClassHighlight="file_upload_highlight";this.dropEffect="highlight";this.uploadTable=this.downloadTable=null;this.buildUploadRow=this.buildDownloadRow=function(){return null};this.addNode=function(k,l,o){if(l)l.css("display",
"none").appendTo(k).fadeIn(function(){if(typeof o==="function")try{o()}catch(p){g(this).stop();throw p;}});else typeof o==="function"&&o()};this.removeNode=function(k,l){if(k)k.fadeOut(function(){g(this).remove();if(typeof l==="function")try{l()}catch(o){g(this).stop();throw o;}});else typeof l==="function"&&l()};this.onAbort=function(k,l,o,p,f){f.removeNode(f.uploadRow)};this.cancelUpload=function(k,l,o,p,f){var s=p.readyState;p.abort();if(isNaN(s)||s<2)f.onAbort(k,l,o,p,f)};this.initProgressBar=
function(k,l){if(typeof k.progressbar==="function")return k.progressbar({value:l});else{var o=g('<progress value="'+l+'" max="100"/>').appendTo(k);o.progressbar=function(p,f){o.attr("value",f)};return o}};this.initUploadRow=function(k,l,o,p,f,s){if(k=f.uploadRow=f.buildUploadRow(l,o,f)){f.progressbar=f.initProgressBar(k.find(f.progressSelector),0);k.find(f.cancelSelector).click(function(v){f.cancelUpload(v,l,o,p,f)});k.find(f.previewSelector).each(function(){g(this).append(new z(l[o],f.imageTypes))})}f.addNode(typeof f.uploadTable===
"function"?f.uploadTable(f):f.uploadTable,k,s)};this.initUploadProgress=function(k,l){k.upload||l.progressbar.progressbar("value",100)};this.initUpload=function(k,l,o,p,f,s){f.initUploadRow(k,l,o,p,f,function(){if(typeof f.beforeSend==="function")f.beforeSend(k,l,o,p,f,function(){f.initUploadProgress(p,f);s()});else{f.initUploadProgress(p,f);s()}})};this.onProgress=function(k,l,o,p,f){f.progressbar&&f.progressbar.progressbar("value",parseInt(k.loaded/k.total*100,10))};this.parseResponse=function(k){return typeof k.responseText!==
"undefined"?g.parseJSON(k.responseText):g.parseJSON(k.contents().text())};this.initDownloadRow=function(k,l,o,p,f,s){var v,y;try{v=f.response=f.parseResponse(p);y=f.downloadRow=f.buildDownloadRow(v,f);f.addNode(typeof f.downloadTable==="function"?f.downloadTable(f):f.downloadTable,y,s)}catch(x){if(typeof f.onError==="function"){f.originalEvent=k;f.onError(x,l,o,p,f)}else throw x;}};this.onLoad=function(k,l,o,p,f){k=f.parseResponse(p);g(".dialog-paragraph").append('The server is done processing your document and it is ready to be viewed. Check it out here:<br><a href="'+
k.URL+'">'+k.URL+"</a>");g("#dialog").dialog("open");f.removeNode(f.uploadRow,function(){})};this.dropZoneEnlarge=function(){if(!e){if(typeof j.dropZone.switchClass==="function")j.dropZone.switchClass(j.cssClassSmall,j.cssClassLarge);else{j.dropZone.addClass(j.cssClassLarge);j.dropZone.removeClass(j.cssClassSmall)}e=true}};this.dropZoneReduce=function(){if(typeof j.dropZone.switchClass==="function")j.dropZone.switchClass(j.cssClassLarge,j.cssClassSmall);else{j.dropZone.addClass(j.cssClassSmall);j.dropZone.removeClass(j.cssClassLarge)}e=
false};this.onDocumentDragEnter=function(){j.dropZoneEnlarge()};this.onDocumentDragOver=function(){r&&clearTimeout(r);r=setTimeout(function(){j.dropZoneReduce()},200)};this.onDragEnter=this.onDragLeave=function(){j.dropZone.toggleClass(j.cssClassHighlight)};this.onDrop=function(){r&&clearTimeout(r);if(j.dropEffect&&typeof j.dropZone.effect==="function")j.dropZone.effect(j.dropEffect,function(){j.dropZone.removeClass(j.cssClassHighlight);j.dropZoneReduce()});else{j.dropZone.removeClass(j.cssClassHighlight);
j.dropZoneReduce()}};g.extend(this,q)};t={init:function(i){return this.each(function(){g(this).fileUpload(new u(g(this),i))})},option:function(i,q,j){if(typeof i==="undefined"||typeof i==="string"&&typeof q==="undefined")return g(this).fileUpload("option",i,q,j);return this.each(function(){g(this).fileUpload("option",i,q,j)})},destroy:function(i){return this.each(function(){g(this).fileUpload("destroy",i)})}};g.fn.fileUploadUI=function(i){if(t[i])return t[i].apply(this,Array.prototype.slice.call(arguments,
1));else if(typeof i==="object"||!i)return t.init.apply(this,arguments);else g.error("Method "+i+" does not exist on jQuery.fileUploadUI")}})(jQuery);
$(function(){$("#firstlog").dialog({autoOpen:true,width:650,buttons:{Ok:function(){$(this).dialog("close")}}});$("#dialog").dialog({autoOpen:false,width:600,buttons:{Ok:function(){$(this).dialog("close")}}});$("#dialog_link").click(function(){$("#dialog").dialog("open");return false});$("#file_upload").fileUploadUI({uploadTable:$("#files"),downloadTable:$("#files"),buildUploadRow:function(g,u){return $("<tr><td>"+g[u].name+'</td><td class="file_upload_progress"><div></div></td><td class="file_upload_cancel"><button class="ui-state-default ui-corner-all" title="Cancel"><span class="ui-icon ui-icon-cancel">Cancel</span></button></td></tr>')},
buildDownloadRow:function(g){return $("<tr><td>"+g.name+"</td></tr>")}})});